apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: multi-k8s
build:
  local:
    push: false
  artifacts:
  - image: dappilik/multi-client
    context: client
    docker:
      dockerfile: Dockerfile.dev
    sync:
      manual:
        - src: "src/**/*.js"
          dest: .
        - src: "src/**/*.css"
          dest: .
        - src: "src/**/*.html"
          dest: .
  - image: dappilik/multi-server
    context: server
    docker:
      dockerfile: Dockerfile.dev
    sync:
      manual:
        - src: "*.js"
          dest: .
  - image: dappilik/multi-worker
    context: worker
    docker:
      dockerfile: Dockerfile.dev
    sync:
      manual:
        - src: "*.js"
          dest: .
deploy:
  kubectl:
    manifests:
    - k8s/client-cluster-ip-service.yaml
    - k8s/client-deployment.yaml
    - k8s/database-persistent-volume-claim.yaml
    - k8s/ingress-service.yaml
    - k8s/postgres-cluster-ip-service.yaml
    - k8s/postgres-deployment.yaml
    - k8s/redis-cluster-ip-service.yaml
    - k8s/redis-deployment.yaml
    - k8s/server-cluster-ip-service.yaml
    - k8s/server-deployment.yaml
    - k8s/worker-deployment.yaml
